echo ===== START INSTALLING NPM MODULES in $PWD =====
echo START INSTALLING NPM Modules in $PWD
CURR_DIR=$PWD
# echo START INSTALLING NPM Modules in $SPCOIN_BE_PATH
# cd $SPCOIN_BE_PATH
# npm i
echo START INSTALLING NPM Modules in $SPCOIN_FE_PATH
cd $SPCOIN_FE_PATH
npm i 
cd $CURR_DIR
echo FINISHED INSTALLING NPM Modules in $PWD
echo ===== FINISHED INSTALLING NPM MODULES in $PWD =====
